/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
        dark: "#232A3C",
        medium: "#293245",
        "custom-gray": "#ededed",
        "custom-red": "#820924",
        "blue-grtpe": "#1b3f85",
        "mi-carrera-blue": "#0075C9",
        "mi-carrera-red": "#e22321",
        "custom-black": "#1f2937",
        "red-gore-1":"#9e0c26",
        "red-gore-2":"#820924",
        "red-gore-3":"#c20831",
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      arima: ["Arima", "sans-serif"],
      redhat: ['Red Hat Display', 'sans-serif'],
    },
  },
  plugins: [],
};
